sudo: false
language: node_js
env:
  - PUBLISH_FROM_NODE_VERSION=8.10
node_js:
  - "8.10"
  - "10.0"
  - "12.0"
  - "lts/*"
  - "node"

before_install:
  - npm install -g npm@latest

install:
  - npm ci

after_success:
  - npm run doc
  - ./travis/.travis_publish

before_deploy:
  - node ./travis/bumpversion.js
deploy:
  - provider: npm
    # Do not throw away the updated package.json we generated in `before_deploy`:
    skip_cleanup: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    # Note: do not deploy on pull request, because $TRAVIS_BRANCH will be the target branch.
    tag: "$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: $TRAVIS_NODE_VERSION = $PUBLISH_FROM_NODE_VERSION

cache:
  directories:
    - node_modules
